#!/usr/bin/env node
/**
 * Secret-leak verifier.
 *
 * Three separate failures, all of which are unrecoverable once pushed:
 *
 *  1. A credential committed to the repository. Rotating is the only fix, and
 *     it has to happen before the commit lands, not after.
 *
 *  2. A server secret referenced from client code. Anything a mobile or web
 *     bundle reads is readable by anyone holding the binary, so only the
 *     `EXPO_PUBLIC_*` / `NEXT_PUBLIC_*` prefixes may appear there. A bare
 *     `process.env.GOOGLE_CLIENT_SECRET` in a screen is a shipped secret even
 *     if the value is only set in CI.
 *
 *  3. A public-prefixed variable holding something that should not be public.
 *     `EXPO_PUBLIC_..._SECRET` is a contradiction; naming it that way means
 *     someone will eventually fill it in.
 *
 * `.env.example` is scanned too — it must stay a template with empty values.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** This file quotes the patterns it bans, so it excludes itself. */
const SELF = path.join(root, 'scripts', 'check-secrets.mjs')

const SCAN_DIRS = ['apps', 'packages', 'supabase', 'scripts', '.github']
const SCAN_FILES = ['.env.example']

const SCANNED_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.json',
  '.sql',
  '.yml',
  '.yaml',
  '.kt',
  '.swift',
  '.gradle',
  '.plist',
  '.xml',
  '.md',
  '.example',
])

const SKIP_DIRS = new Set([
  'node_modules',
  '.next',
  '.expo',
  'dist',
  'build',
  'ios',
  'android',
  'coverage',
])

/** Files whose whole purpose is to name secrets, without holding any. */
const NAMING_ONLY = [/^\.env\.example$/, /^docs\//, /^README\.md$/, /^\.github\/workflows\//]

function walk(dir, out = []) {
  let entries
  try {
    entries = readdirSync(dir)
  } catch {
    return out
  }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry)) continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) {
      // `apps/mobile/ios` and `android` are generated by prebuild and are not
      // checked in; the module's own native sources live under modules/.
      if (entry.startsWith('.') && entry !== '.github' && entry !== '.maestro') continue
      walk(full, out)
    } else if (SCANNED_EXTENSIONS.has(path.extname(entry)) || entry === '.env.example') {
      out.push(full)
    }
  }
  return out
}

// ── 1. Committed credentials ────────────────────────────────────────────────

const CREDENTIAL_PATTERNS = [
  { name: 'private key block', pattern: /-----BEGIN (RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----/ },
  { name: 'AWS access key id', pattern: /\bAKIA[0-9A-Z]{16}\b/ },
  { name: 'Google API key', pattern: /\bAIza[0-9A-Za-z_-]{35}\b/ },
  { name: 'Google OAuth client secret', pattern: /\bGOCSPX-[0-9A-Za-z_-]{20,}/ },
  { name: 'Slack token', pattern: /\bxox[abprs]-[0-9A-Za-z-]{10,}/ },
  { name: 'Stripe live key', pattern: /\b[sr]k_live_[0-9A-Za-z]{16,}/ },
  { name: 'OpenAI key', pattern: /\bsk-(proj-)?[A-Za-z0-9_-]{32,}/ },
  { name: 'Anthropic key', pattern: /\bsk-ant-[A-Za-z0-9_-]{32,}/ },
  { name: 'RevenueCat secret key', pattern: /\bsk_[A-Za-z0-9]{24,}\b/ },
  { name: 'GitHub token', pattern: /\bgh[pousr]_[A-Za-z0-9]{36,}/ },
  { name: 'Supabase service-role JWT', pattern: /\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{40,}\./ },
  {
    name: 'inline password assignment',
    // A URL is excluded: `token: 'https://oauth2.googleapis.com/token'` is an
    // endpoint, and endpoints are exactly what a field called `token` holds in
    // an OAuth configuration.
    pattern:
      /\b(password|passwd|secret|api_?key|token)\s*[:=]\s*["'`](?!https?:\/\/)[^"'`\s{$]{12,}["'`]/i,
  },
]

/**
 * The local Supabase stack ships with a fixed, publicly documented password
 * and demo JWTs. They unlock nothing but a container on the developer's own
 * machine, and the connection string has to be written down somewhere. Test
 * fixtures are allowed on the same footing, but only when the value itself
 * says so — a real credential does not contain the word "fixture".
 */
const LOCAL_DEV_VALUES =
  /(postgres:postgres@(127\.0\.0\.1|localhost)|supabase_admin|:54322|demo-anon-key|test[-_]?secret|example\.com|fake|fixture|dummy)/i

// ── 2. Server secrets referenced from client code ───────────────────────────

const CLIENT_TREES = [
  /^apps\/mobile\/(app|src|modules)\//,
  /^apps\/web\/src\//,
  // Every shared package is consumed as source by the mobile app, so anything
  // it reads is compiled into the binary just the same.
  /^packages\//,
]

/** Read from the template so the two lists cannot drift apart. */
function serverSecretNames() {
  const text = readFileSync(path.join(root, '.env.example'), 'utf8')
  const names = new Set()
  for (const line of text.split('\n')) {
    const match = /^([A-Z][A-Z0-9_]*)=/.exec(line.trim())
    if (!match) continue
    const name = match[1]
    if (name.startsWith('EXPO_PUBLIC_') || name.startsWith('NEXT_PUBLIC_')) continue
    names.add(name)
  }
  return names
}

/**
 * Next.js server components legitimately read server env vars: they run on the
 * server and never reach the browser bundle. Route handlers likewise.
 */
const SERVER_SIDE_WEB = /^apps\/web\/src\/app\/[^]*\/(route|opengraph-image|sitemap|robots)\.tsx?$/

// ── 3. Public-prefixed variables that should not be public ──────────────────

const PUBLIC_BUT_SECRET =
  /\b(EXPO_PUBLIC|NEXT_PUBLIC)_[A-Z0-9_]*(SECRET|PRIVATE_KEY|SERVICE_ROLE|PASSWORD)[A-Z0-9_]*\b/

// ── Run ─────────────────────────────────────────────────────────────────────

const serverSecrets = serverSecretNames()
const offenders = []

const files = [
  ...SCAN_DIRS.flatMap((dir) => walk(path.join(root, dir))),
  ...SCAN_FILES.map((file) => path.join(root, file)),
]

for (const file of files) {
  if (file === SELF) continue
  const relative = path.relative(root, file)
  let text
  try {
    text = readFileSync(file, 'utf8')
  } catch {
    continue
  }
  const namingOnly = NAMING_ONLY.some((allow) => allow.test(relative))
  const isClient = CLIENT_TREES.some((tree) => tree.test(relative)) && !SERVER_SIDE_WEB.test(relative)

  text.split('\n').forEach((line, index) => {
    const at = `${relative}:${index + 1}`

    if (!namingOnly && !LOCAL_DEV_VALUES.test(line)) {
      for (const credential of CREDENTIAL_PATTERNS) {
        if (credential.pattern.test(line)) {
          offenders.push({ at, rule: `committed credential (${credential.name})` })
        }
      }
    }

    if (PUBLIC_BUT_SECRET.test(line)) {
      offenders.push({
        at,
        rule: 'a secret-sounding value behind a public env prefix — public values ship in the bundle',
      })
    }

    if (isClient) {
      for (const match of line.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)/g)) {
        const name = match[1]
        if (serverSecrets.has(name)) {
          offenders.push({ at, rule: `client code reads the server secret ${name}` })
        }
      }
    }
  })

  // `.env.example` is a template. Non-secret defaults (a model name, a bundle
  // id, the local database URL) are useful and stay; anything whose *name*
  // says credential must ship blank, so that copying the template can never
  // activate someone else's project.
  if (relative === '.env.example') {
    const SECRET_NAME = /(SECRET|_KEY|KEY_|PASSWORD|TOKEN|SERVICE_ROLE|CLIENT_ID|WEBHOOK)/
    // `*_VERSION` and `*_MODEL` name a setting *about* a credential, not the
    // credential: the key rotation version has to have a default to be useful.
    const NOT_A_CREDENTIAL = /_(VERSION|MODEL|URL|URI|ENABLED)$/
    text.split('\n').forEach((line, index) => {
      const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line.trim())
      if (!match) return
      const [, name, rawValue] = match
      const value = rawValue.trim()
      if (value === '' || !SECRET_NAME.test(name) || NOT_A_CREDENTIAL.test(name)) return
      // A placeholder is fine as long as it is unmistakably one.
      if (/^<.+>$/.test(value)) return
      offenders.push({
        at: `.env.example:${index + 1}`,
        rule: `${name} carries a value; a credential in the template must ship blank`,
      })
    })
  }
}

if (offenders.length > 0) {
  console.error(`Secret check failed: ${offenders.length} problem(s).\n`)
  for (const offender of offenders) {
    console.error(`  ${offender.at}\n    ${offender.rule}\n`)
  }
  process.exit(1)
}

console.log(
  `Secret check passed: no committed credentials, and no client reference to any of the ${serverSecrets.size} server secrets.`,
)
